project_id = "upjtsekkpjgikrrlfoxv"
 
[functions.check-tender-links]
verify_jwt = false

[functions.export-data-backup]
verify_jwt = false

[functions.admin-get-signups]
verify_jwt = false

[functions.check-hearing-reminders]
verify_jwt = false
