project_id = "upjtsekkpjgikrrlfoxv"
 
[functions.check-tender-links]
verify_jwt = false

[functions.export-data-backup]
verify_jwt = false

[functions.admin-get-signups]
verify_jwt = false

[functions.check-hearing-reminders]
verify_jwt = false

[functions.create-staff-account]
verify_jwt = false

[functions.process-recurring-documents]
verify_jwt = false

[functions.admin-get-tenant-data]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-sms-on-notification]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false
